services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: es-nl
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: always